Repository Step3-kakao-tech-campus/Team15_FE, pull requests merged in 2023-10, with the labels that each got.

#19 [FE/09] 페이머니 화면
  src/pages/PayMoney.page.jsx
Labels: feature✨

#28 [FE/09] 페이머니 페이지 _ 상단부분 완성
  router/router.jsx
  src/components/common/Button.component.jsx
  src/components/paymoney/MoneyHistory.jsx
  src/components/paymoney/MyMoney.css
  src/components/paymoney/MyMoney.jsx
  src/pages/Charge.page.jsx
  src/pages/My.page.jsx
  src/pages/PayMoney.page.jsx
Labels: feature✨

#30 [FE/05] 결제 페이지입니다.
  package.json
  pnpm-lock.yaml
  src/apis/paymoney.js
  src/components/common/Button.component.jsx
  src/components/common/Modal.component.jsx
  src/components/payment/AnounceCanPayment.component.jsx
  src/components/payment/PayButton.component.jsx
  src/components/payment/Payment.component.jsx
  src/components/payment/Product.component.jsx
  src/components/rent/Calender.component.jsx
  src/components/rent/calender.css
  src/pages/PayMoney.page.jsx
  src/pages/Payment.page.jsx
  src/pages/Rent.page.jsx
  src/stores/rent.atom.js
Labels: feature✨

#29 [FE/07] 화면 구성
  public/images/logo.png
  router/router.jsx
  src/components/sign/Information.component.jsx
  src/components/sign/Input.component.jsx
  src/components/sign/SlidePannel.component.jsx
  src/pages/Account.page.jsx
  src/pages/School.page.jsx
  src/pages/SchoolCard.page.jsx
  src/pages/Signin.page.jsx
  src/pages/Signup.page.jsx
Labels: feature✨

#31 [FE/06] 결제페이지
  postcss.config.js
  src/apis/paymoney.js
  src/components/common/AppBar.component.jsx
  src/components/common/BottomFullLink.component.jsx
  src/components/common/Button.component.jsx
  src/components/common/Modal.component.jsx
  src/components/payment/PayButton.component.jsx
  src/components/payment/Payment.component.jsx
  src/components/payment/Product.component.jsx
  src/components/product/Detail.component.jsx
  src/components/product/Item.component.jsx
  src/components/rent/Calender.component.jsx
  src/pages/Rent.page.jsx
Labels: feature✨, refactor♻️

#34 [FE/07],[FE/08] 로그인 페이지, 이메일 페이지 컴포넌트 적용
  router/router.jsx
  src/components/common/Icon.component.jsx
  src/components/sign/Information.component.jsx
  src/components/sign/Input.component.jsx
  src/pages/Account.page.jsx
  src/pages/School.page.jsx
  src/pages/SchoolCard.page.jsx
  src/pages/Signin.page.jsx
  src/pages/Signup.page.jsx
  src/pages/signup/Account.page.jsx
  src/pages/signup/School.page.jsx
  src/pages/signup/SchoolCard.page.jsx
  src/pages/signup/Signup.page.jsx
Labels: feature✨, refactor♻️

#33 [FE/09],[FE/11] 페이머니 페이지, 출금 화면 완료
  router/router.jsx
  src/components/common/Button.component.jsx
  src/components/common/Txt.component.jsx
  src/components/paymoney/MoneyHistory.jsx
  src/components/paymoney/MyMoney.jsx
  src/pages/Charge.page.jsx
  src/pages/My.page.jsx
  src/pages/PayMoney.page.jsx
Labels: feature✨

#35 [FE/12] 대여내역 페이지 컴포넌트 적용
  .eslintrc.cjs
  index.html
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  pnpm-lock.yaml
  router/index.jsx
  router/product.router.jsx
  router/router.jsx
  router/sign.router.jsx
  src/App.jsx
  src/apis/paymoney.js
  src/apis/rental.js
  src/components/common/AppBar.component.jsx
  src/components/common/MainContainer.component.jsx
  src/components/common/Txt.component.jsx
  src/components/home/Header.component.jsx
  src/components/home/Menu.component.jsx
  src/components/product/List.component.jsx
  src/components/product/rentPeriod/Calender.component.jsx
  src/components/product/rentPeriod/calender.css
  src/components/rental/Item/Rental.component.jsx
  src/components/rental/Item/RentalComplete.component.jsx
  src/components/rental/Item/RentalSchedule.component.jsx
  src/components/rental/Item/index.component.jsx
  src/components/rental/List.component.jsx
  src/functions/rental.js
  src/pages/Charge.page.jsx
  src/pages/Home.page.jsx
  src/pages/My.page.jsx
  src/pages/PayMoney.page.jsx
  src/pages/ProductDetail.page.jsx
  src/pages/RentalList.page.jsx
  src/pages/product/Payment.page.jsx
  src/pages/product/ProductDetail.page.jsx
  src/pages/product/ProductRent.page.jsx
  src/types/rental.d.ts
Labels: feature✨

#44 [FE/15] 리뷰페이지
  router/index.jsx
  router/sign.router.jsx
  src/apis/rental.js
  src/components/common/BottomFullLink.component.jsx
  src/components/common/Icon.component.jsx
  src/components/common/Link.component.jsx
  src/components/common/MainContainer.component.jsx
  src/components/common/Modal.component.jsx
  src/components/home/Menu.component.jsx
  src/components/payment/Payment.component.jsx
  src/components/paymoney/MyMoney.jsx
  src/components/rental/Item/Rental.component.jsx
  src/components/rental/Item/RentalComplete.component.jsx
  src/components/rental/Item/RentalSchedule.component.jsx
  src/components/rental/Item/index.component.jsx
  src/components/rental/List.component.jsx
  src/components/review/QuickReview.component.jsx
  src/components/review/Review.component.jsx
  src/components/review/Stars.component.jsx
  src/components/review/TextArea.component.jsx
  src/pages/Home.page.jsx
  src/pages/PayMoney.page.jsx
  src/pages/RentalList.page.jsx
  src/pages/Review.page.jsx
  src/pages/sign/Account.page.jsx
  src/pages/sign/School.page.jsx
  src/pages/sign/SchoolCard.page.jsx
  src/pages/sign/Signin.page.jsx
  src/pages/sign/Signup.page.jsx
  src/stores/review.atom.js
Labels: feature✨

#49 [FE/17] 키패드 안되는 문제와 일부 CSS를 수정하였습니다.
  router/index.jsx
  src/components/common/Button.component.jsx
  src/components/common/Errorboundary.component.jsx
  src/components/common/Link.component.jsx
  src/components/common/Txt.component.jsx
  src/components/payment/Payment.component.jsx
  src/components/payment/Product.component.jsx
  src/components/paymoney/ChargeMoney.jsx
  src/components/paymoney/KeyPad.jsx
  src/components/paymoney/MoneyHistory.jsx
  src/components/paymoney/MyMoney.jsx
  src/components/product/Detail.component.jsx
  src/components/product/List.component.jsx
  src/components/rental/Item/Rental.component.jsx
  src/components/rental/Item/RentalComplete.component.jsx
  src/components/rental/Item/RentalSchedule.component.jsx
  src/components/rental/List.component.jsx
  src/hooks/useProductQuery.jsx
  src/hooks/useRentalQuery.jsx
  src/pages/Charge.page.jsx
  src/pages/Home.page.jsx
  src/pages/PayMoney.page.jsx
  src/pages/RentalList.page.jsx
  src/pages/product/Payment.page.jsx
  src/pages/product/ProductDetail.page.jsx
  src/stores/paymoney.atom.js
Labels: refactor♻️

#47 [FE/16] 멘토님께서 이야기 해주신 부분 refactoring 진행했습니다
  router/index.jsx
  router/sign.router.jsx
  src/apis/rental.js
  src/components/common/BottomFullLink.component.jsx
  src/components/common/Button.component.jsx
  src/components/common/Errorboundary.component.jsx
  src/components/common/Icon.component.jsx
  src/components/common/Link.component.jsx
  src/components/common/MainContainer.component.jsx
  src/components/common/Modal.component.jsx
  src/components/home/Menu.component.jsx
  src/components/payment/Payment.component.jsx
  src/components/payment/Product.component.jsx
  src/components/paymoney/MyMoney.jsx
  src/components/product/Detail.component.jsx
  src/components/product/List.component.jsx
  src/components/rental/Item/Rental.component.jsx
  src/components/rental/Item/RentalComplete.component.jsx
  src/components/rental/Item/RentalSchedule.component.jsx
  src/components/rental/Item/index.component.jsx
  src/components/rental/List.component.jsx
  src/components/review/QuickReview.component.jsx
  src/components/review/Review.component.jsx
  src/components/review/Stars.component.jsx
  src/components/review/TextArea.component.jsx
  src/hooks/useProductQuery.jsx
  src/hooks/useRentalQuery.jsx
  src/pages/Home.page.jsx
  src/pages/PayMoney.page.jsx
  src/pages/RentalList.page.jsx
  src/pages/Review.page.jsx
  src/pages/product/Payment.page.jsx
  src/pages/product/ProductDetail.page.jsx
  src/pages/sign/Account.page.jsx
  src/pages/sign/School.page.jsx
  src/pages/sign/SchoolCard.page.jsx
  src/pages/sign/Signin.page.jsx
  src/pages/sign/Signup.page.jsx
  src/stores/review.atom.js
Labels: refactor♻️

#52 [FE/08] 회원가입 페이지 정규표현식 적용
  src/components/sign/Input.component.jsx
  src/pages/signup/Account.page.jsx
  src/pages/signup/School.page.jsx
  src/pages/signup/SchoolCard.page.jsx
  src/pages/signup/Signup.page.jsx
Labels: feature✨

#54 [FE/18] MSW를 개발하였습니다.
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/components/home/Category.component.jsx
  src/main.jsx
  src/mocks/browser.js
  src/mocks/handlers/category.mocks.js
  src/mocks/handlers/index.js
  src/mocks/handlers/payment.mocks.js
  src/mocks/handlers/product.mocks.js
  src/mocks/handlers/rental.mocks.js
  src/mocks/handlers/review.mocks.js
  src/mocks/handlers/user.mocks.js
Labels: feature✨

#57 전남대_15조_BorrowMe_6주차
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/components/common/Link.component.jsx
  src/components/common/Txt.component.jsx
  src/components/home/Category.component.jsx
  src/components/paymoney/ChargeMoney.jsx
  src/components/paymoney/KeyPad.jsx
  src/components/paymoney/MoneyHistory.jsx
  src/components/paymoney/MyMoney.css
  src/components/paymoney/MyMoney.jsx
  src/components/sign/Input.component.jsx
  src/hooks/useProductQuery.jsx
  src/main.jsx
  src/mocks/browser.js
  src/mocks/handlers/category.mocks.js
  src/mocks/handlers/index.js
  src/mocks/handlers/payment.mocks.js
  src/mocks/handlers/product.mocks.js
  src/mocks/handlers/rental.mocks.js
  src/mocks/handlers/review.mocks.js
  src/mocks/handlers/user.mocks.js
  src/pages/Charge.page.jsx
  src/pages/PayMoney.page.jsx
  src/pages/signup/Account.page.jsx
  src/pages/signup/School.page.jsx
  src/pages/signup/SchoolCard.page.jsx
  src/pages/signup/Signup.page.jsx
  src/stores/paymoney.atom.js
Labels: Request Review

#64 [FE07] 피드백 적용
  package-lock.json
  src/components/sign/Input.component.jsx
  src/pages/signup/Account.page.jsx
Labels: refactor♻️

#68 [FE/21] 에러 케이스 점검 했습니다.
  package.json
  src/App.jsx
  src/components/common/Errorboundary.component.jsx
  src/constants/errorCase.js
  src/functions/axios.js
  src/stores/global.atom.js
Labels: feature✨
